### ISSUE TITLE
new project confusion

### ISSUE THREAD

**Issue by galgalesh** [alexandervdm/gummi#1]
The project support is very confusing. You can open a project but not create a new project?
- If project aren't supported at all, I'd recommend removing the menu item.
- If you have to create the project files by hand or in another way, I'd recommend linking to a guide on how to do this.

I wouldn't mind having to create project files by hand, but I have no idea how to, and if this is even possible...

**Comment by pedro132** [comment]
If you mouse-over the create new project entry, a tooltip appears saying "This function requires an active document".

So having a file already open in the editor allows the creation of a project.

**Comment by galgalesh** [comment]
This is not the case in Gummi in Ubuntu 14.04. Version 0.6.5

Tooltip does not show and create project stays greyed out, even with an
active document.

2015-03-26 15:45 GMT+01:00 pedro132 <notifications@github.com>:

**Comment by pedro132** [comment]
I just tried it again and it only works if the current document exists, meaning, if it was already saved.

[Screenshot 1](https://www.dropbox.com/s/xv2zajwd5bwxsxr/screenshot1.png?dl=1)
[Screenshot 2](https://www.dropbox.com/s/ihe8m6clcvshh1d/screenshot2.png?dl=1)

I'm also version 0.6.5 of Gummi.

**Comment by galgalesh** [comment]
This is not the case with me.... I tried after opening an existing
document. I also tried after saving the default document.

2015-03-26 16:56 GMT+01:00 pedro132 <notifications@github.com>:

**Comment by pedro132** [comment]
That is weird... For reference, the exact package version I have installed is 0.6.5-3.

And well, if you want a workaround, I created a project and got this in the .gummi project file:
```
version=0.6.0
typesetter=pdflatex
steps=texpdf
root=/tmp/test.tex
```

**Comment by alexandervdm** [comment]
It's been a while since you reported this (apologies), but currently I'm unable to reproduce your issue of the missing tooltip. Please re-open if this still occurs on the latest release. For more information on project creation, please see the wiki.

**Comment by botcs** [comment]
Yeah, this is still the problem.

**Comment by ljsr** [comment]
I've the 0.6.5 version from ubuntu repositories (in the about window appear gummi.midnightcoding.com) and closing all the documents the project options menu appear disabled. I think that if I have a project, the option "open project" could be active because allways I will need to create a empty document for to activate the "open project" option.

Thanks
