### ISSUE TITLE
Compile failor when using minted package

### ISSUE THREAD

**Issue by zoj613** [alexandervdm/gummi#100]
Everytime I use the minted package inside Gummi it fails to compile no matter what I do. It gives me this error every single time:

`Package minted Error: Missing Pygments output; \inputminted 
was
probably given a file that does not exist--otherwise, you may need 
the outputdir package option, or may be using an incompatible build tool,
or may be using frozencache with a missing file.

See the minted package documentation for explanation.`

what can i do to fix this? It compiles fine on TexStudio and other editors

**Comment by xtsm** [comment]
Same problem.
I've also noticed that it somehow doesn't occur when you copy your code into an unsaved file and compile it without saving. Then it works properly. Once you save this file, you get this error.

**Comment by hhg7** [comment]
I've had this problem as well.  I've opened an issue on https://tex.stackexchange.com/questions/517437/gummi-cannot-compile-with-minted-package-but-can-compile-at-command-line
