### ISSUE TITLE
Zoom level in preview plane reverts to default when switching between documents

### ISSUE THREAD

**Issue by tonysf** [alexandervdm/gummi#101]
I use Gummi for academic LaTeXing and it's a great program, I've used it for at least 4 years now. However, I have a high DPI setup (1440p) and the default zoom level (100%) on the preview pane is quite bad for this. Changing it is no problem but if I switch documents Gummi reverts back to the default zoom level instead of 'remembering' what zoom I had chosen for this document. I am also unable to change the default zoom level (this would be a sufficient fix for my problem as I view all my previews in 200%).

**Comment by alexandervdm** [comment]
Super annoying limitation! The partial fix to store the configured zoom mode per tab/document has been committed in 87b701857e31435a11cf53d30af69cbacfcf03b6. The scrollbars are still all over the place when one switches documents, but that ties more into #15. 

Adding the ability to set a global default zoom mode later this weekend.

**Comment by tonysf** [comment]
Awesome!!! Thanks so much for taking the time do this and for writing such a useful software, I use it every day. Please let me know if there is somewhere I can donate to you for this work.

**Comment by alexandervdm** [comment]
You're most welcome. A configurable zoom mode setting was added in 18e8d6d4ac12f9bcae644246b578e7b9d154c436. I might set up some methods to support the project again at some point, but right now this is not available or necessary. Glad you find Gummi useful and thanks for reporting this issue.
