### ISSUE TITLE
PDF preview is out of sync with the document

### ISSUE THREAD

**Issue by btlvr** [alexandervdm/gummi#102]
Lately I have been having an issue that has made gummi practically unusable. 

Every time the preview updates, it's "behind" the actual document. For example, if I remove a section and put it back, it always displays the wrong thing. When the section is there, it does not show it (and vice versa). 

Another example is if I have a section and start adding letters to it, the preview always only shows the last edit that triggered the preview.

**Comment by btlvr** [comment]
[Here](https://streamable.com/s/3xh1a/sgvaqy) is a video of this issue happening

**Comment by alexandervdm** [comment]
Can you tell me your OS and gummi version?

**Comment by alexandervdm** [comment]
Closing because (due to the black border around the PDF) I suspect you are/were using an unofficial fork.
