### ISSUE TITLE
Upon closing the Find window, caret jumps to the next search result

### ISSUE THREAD

**Issue by amitwol** [alexandervdm/gummi#103]
It makes you work on the part needed keeping the Find window open, and is quite annoying. Happens except for the last result in the file, and only when using the Esc key (closing with clicking on the window's X button does not trigger that)

**Comment by tonysf** [comment]
I also experience this issue. You can train yourself to do ctrl+shift+g after hitting escape in the mean time like I have.

**Comment by alexandervdm** [comment]
Fixed, thanks for reporting!
