### ISSUE TITLE
Directory Pollution

### ISSUE THREAD

**Issue by jackdesert** [alexandervdm/gummi#107]
When I edit a myfile.tex file, gummi creates some extra files in the same directory:

    myfile.synctex.gz
    myfile.log
    myfile.aux

I would rather not see these files, or at least rather not see them in the same directory where my .tex file lives. 

How about an option that puts these somewhere in the /tmp directory instead?

**Comment by alexandervdm** [comment]
We actually used to store these files in /tmp, but that led to two problems - iirc:

1. LaTeX compiling would fail in many circumstances when working files such as the ones you mention would not share a basepath with the in- and output file. 
2. Security issues on multi-user systems (see debian bug [756432](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=756432))
