### ISSUE TITLE
Preview Page should follow the cursor on the Edit page

### ISSUE THREAD

**Issue by cervere** [alexandervdm/gummi#109]
In a fairly long .tex file, can the Preview page directly go to the page where the cursor is currently present on the Edit page...

Is it already possible?

Thanks in advance, appreciate Gummi a lot already.

**Comment by alexandervdm** [comment]
Yes, you can do this by enabling SyncTeX in the compilation options and then making sure the 'Sync preview with Editor' option is enabled in the View menu. Enjoy :)
