### ISSUE TITLE
File > Open doesn't work for project files

### ISSUE THREAD

**Issue by mlda065** [alexandervdm/gummi#11]
Steps to reproduce
---------

* Click *File* -> *Open*
* Select an existing *project* file (`*.gummi`)

Expected Behaviour
---------

Gummi recognises that this is a project file, and executes the same behaviour as *Project* -> *Open Project*.

Observed Behaviour
---------

Gummi treats the file like a `*.txt*` or `*.tex` file. It is displayed as a normal plaintext file.

![screenshot from 2015-08-29 13 11 15](https://cloud.githubusercontent.com/assets/7035647/9560292/7e9eb6d4-4e4f-11e5-9962-8b0c8d6ea071.png)

**Comment by alexandervdm** [comment]
I modified the behaviour in d6d436d5c156d4fd6d517175e132240179ffad1f to not allow loading files other than .tex through File->Open. Thank you!
