### ISSUE TITLE
Shortcut CTRL+B / CTRl+I / CTRL+U do not work

### ISSUE THREAD

**Issue by jsuarez314** [alexandervdm/gummi#118]
Hi, 
I had review the code and  the gummi.glade file have a class where the shortcut CTRL+B work to activate the function to bold a selected text. The problem is when I try to bold some text in the gummi interface because this function do not work.

```
<object class="GtkToolButton" id="tool_bold">              
            <property name="visible">True</property>
            <property name="can_focus">False</property>
            <property name="label" translatable="yes">toolbutton5</property>
            <property name="use_underline">True</property>
            <property name="icon_name">format-text-bold</property>
            <signal name="clicked" handler="on_tool_textstyle_bold_activate" swapped="no"/>
            <accelerator key="b" signal="activate" modifiers="GDK_CONTROL_MASK"/>
</object>
```

**Comment by alexandervdm** [comment]
I can't find this line in the 'gummi.glade' versions I checked so far, which is how it should be?

**Comment by jsuarez314** [comment]
Sorry, I was not clear. I thought that this function could be activate adding this line
``<accelerator key="b" signal="activate" modifiers="GDK_CONTROL_MASK"/>``
but this did not work.
