### ISSUE TITLE
Outdated copyright headers

### ISSUE THREAD

**Issue by hlef** [alexandervdm/gummi#121]
Hi,

I saw this during the packaging of 0.7.999:

All files in the source code seem to have `Copyright (C) 2009 Gummi Developers`. This was changed via 5c23788fb20f007c824340a5720430630643fdfa, not sure why. You should maybe opt for 2009-2019 instead. If it's intentional, please ignore/close this bug report.

thanks for your work.

**Comment by alexandervdm** [comment]
I didn't want to update it every year anymore, and according to [this article](http://www.contentious.com/2007/01/07/copyright-notice-is-the-year-really-necessary/) using only the first year of publication is both valid and sufficient. Please re-open if it's not.

**Comment by hlef** [comment]
> I didn't want to update it every year anymore, and according to [this article](http://www.contentious.com/2007/01/07/copyright-notice-is-the-year-really-necessary/) using only the first year of publication is both valid and sufficient. Please re-open if it's not.

Agree, thanks for the explanation!
