### ISSUE TITLE
Unable to change editor font

### ISSUE THREAD

**Issue by wolframw** [alexandervdm/gummi#125]
When I try to change the editor font via the preferences menu, the editor is reset to some fallback font and the following is printed to console:
`(gummi:3860): Gtk-WARNING **: 16:32:48.193: Theme parsing error: <data>:1:19: Junk at end of value for font`
The only font that works is the default "Monospace", I suspect this might be due to whitespaces in other fonts' names.
I'm using version 0.8.0.

**Comment by alexandervdm** [comment]
I see the problem but will make the fix part of 0.8.2 that will be released shortly.

**Comment by alexandervdm** [comment]
Commit 873952a768893e8a24fd05acc5e99e94b946c1ee addresses this problem and should fix your immediate issue, but I'm keeping this open for now to remind myself that we'll need to transition to the new CSS syntax. Thanks for the report.

**Comment by alexandervdm** [comment]
Proper translation to css has been added to be6bc2034d2e8cbaf3f6e3e1050d30a448ae6969 - will be in 0.8.2.
