### ISSUE TITLE
Please consider a flatpak version

### ISSUE THREAD

**Issue by maymage** [alexandervdm/gummi#127]
Hi, thanks for updating gummi!!
Sadly seemingly neither debian, ubuntu nor fedora seem to track your latest update to version 8.1.
Hence would you consider pushing a flatpak version to flathub?

**Comment by btreut** [comment]
> consider pushing a flatpak version to flathub?

Since [Endless OS](https://endlessos.com) allows only the installation of flatpaks, I would also welcome a flatpak for gummi very much. It may build upon the TeXstudio package or share resources with it (see [TeXstudio flatpak](https://github.com/flathub/org.texstudio.TeXstudio)).

**Comment by alexandervdm** [comment]
@farribeiro has created a flatpak for Gummi [here](https://flathub.org/apps/details/app.gummi.gummi). I don't use flatpak myself, but if any of you can verify it works correctly, I'd be happy to link to it.

**Comment by maymage** [comment]
Hi, 

I testing the flatpak version. My papers compile fine. Only issue(s) so far

* https://github.com/alexandervdm/gummi/issues/146 affects the flatpak version. 
    * Workaround: disable the wayland option in flatseal.

**Comment by farribeiro** [comment]
i removed the wayland option in flathub to remedy the reported problem
