### ISSUE TITLE
Dictionaries no longer selectable w/ recent gtkspell and enchant

### ISSUE THREAD

**Issue by tietzc** [alexandervdm/gummi#134]
**Describe the bug**
Since upgrading to gtkspell-3.0.10 and enchant-2 it is no longer possible to select dictionaries in Gummi and `[Error] gtk_spell_checker_set_language (): enchant error for language: None` shows up if spell-checking is enabled. It is still working though if an existing dictionary is set manually in gummi.ini.

**System:**
 - OS: Gentoo
 - Gummi version: 0.8.1

**Comment by alexandervdm** [comment]
This bug made me realize that gummi was still using enchant-1 to fetch the list of dictionaries. I miss Gentoo. Thank you for reporting!

**Comment by oz123** [comment]
@alexandervdm can you release a new version including this fix?
