### ISSUE TITLE
open multiple files from terminal

### ISSUE THREAD

**Issue by gabrieleca** [alexandervdm/gummi#137]
Gummi does not open multiple files from the terminal command line (while it works normally if the file is one).

**System:**
 - OS: Ubuntu 18.0.4
 - Gummi version 0.6.6

**Other**
run gummi with the '--debug' flag for extra information:
$ gummi --debug notes.tex notes2.tex 
[Info] Gummi version: git
[Info] configuration file: /home/gabriele/.config/gummi/gummi.cfg
[Info] Texlive 2017 was found installed..
[Info] Typesetter detected: pdfTeX 3.14159265-2.6-1.40.18 (TeX Live 2017/Debian)
[Info] Typesetter detected: XeTeX 3.14159265-2.6-0.99998 (TeX Live 2017/Debian)
[Info] snippets : /home/gabriele/.config/gummi/snippets.cfg
[Debug] Gummi created!
[Info] using libpoppler 0.62.0
[Debug] GummiGui created!
[Info] Typesetter pdflatex configured.
[Thread][Debug] motion_compile_thread ()
[Thread][Debug] Compile thread sleeping...
[Info] setting styles scheme to tango
[Info] setting font to Monospace 15
[Info] 
[Info] Environment created for:
[Info] TEX: (null)
[Info] TMP: /home/gabriele/.cache/gummi/gummi_ZA45J0
[Info] PDF: /home/gabriele/.cache/gummi/gummi_ZA45J0.pdf
[Debug] motion_do_compile ()
[Thread][Debug] Compile thread awoke.
[Thread][Debug] Document size wrong for fitting, changing scale from 0.000000 to 2.064589.
[Thread][Debug] Compile thread sleeping...
[Debug] motion_do_compile ()
[Thread][Debug] Compile thread awoke.
[Thread][Debug] Compile thread sleeping...

**Comment by alexandervdm** [comment]
Hi @gabrieleca - this feature was added by @florianbegusch for the new 0.8.x series. I recently created an Ubuntu repository to help you upgrade at: https://packages.gummi.app/
