### ISSUE TITLE
Toggleable right panel

### ISSUE THREAD

**Issue by benjaminsaljooghi** [alexandervdm/gummi#138]
Provide the ability to toggle the visibility of the right panel so that users can just work with the editor alone (and use an external PDF viewer).

**Comment by CuddlyCuddlefish** [comment]
This already seems to be available under View > Right Pane. The keyboard shortcut is F8.

**Comment by benjaminsaljooghi** [comment]
I don't see this option in version 0.8.1?

**Comment by alexandervdm** [comment]
I mistakenly thought this feature was not useful to anyone, so I removed it during the transition to GTK3. 
It will be back in the upcoming 0.8.2 release.

**Comment by alexandervdm** [comment]
Feature was reinstated in bf88cbc8aaf6c9c37193c3f1d0c8190bc08d2e7d - building a release today.
