### ISSUE TITLE
Could not locate Glade interface file

### ISSUE THREAD

**Issue by catmanjan** [alexandervdm/gummi#14]
Just followed the compile steps on a fresh copy of Ubuntu 14.04 and got:

jan@u31sd:~/gummi$ cd src
jan@u31sd:~/gummi/src$ ./gummi
Could not locate Glade interface file at:
/usr/share/gummi/ui/gummi.glade

**Comment by alexandervdm** [comment]
My apologies, the steps on the wiki were incomplete. I have made some modifications that complete the compiling process for Gummi.
