### ISSUE TITLE
Spell checking is disabled in Ubuntu 20.04

### ISSUE THREAD

**Issue by mokhtarivahid** [alexandervdm/gummi#140]
Spell checking function is disabled in Ubuntu 20.04.
It is because of the package 'gtkspell' is missing in Ubuntu 20.04!
Is there any solution or alternative?
Best,

**Comment by alexandervdm** [comment]
Ubuntu is offering a broken development build for focal right now and I do not recommend using it. Please see https://bugs.launchpad.net/ubuntu/+source/gummi/+bug/1872667.

**Comment by alexandervdm** [comment]
The official repositories for 20.04 now includes an update for gummi - should be fixed. If not, please re-open.
