### ISSUE TITLE
Gummi crashes when closed with more than one file opened

### ISSUE THREAD

**Issue by the-real-cyberpatrol** [alexandervdm/gummi#143]
Gummi crashes when it get's closed with more than one (saved) file opened. Gummi stays visible, doesn't respond and the process needs to be killed.

When those files are opened after the next start of gummi it asks if the files shall be recovered from the swap files, which works fine.

This happens at least with Xfce.

**Comment by alexandervdm** [comment]
Can you state your OS and gummi version?

**Comment by the-real-cyberpatrol** [comment]
Version: Gummi 0.8.1
Distribution: Arch Linux ARM
Desktop Environment: Xfce
Hardware: Raspberry Pi 4

**Comment by the-real-cyberpatrol** [comment]
This doesn't happen with Gummi 0.6.6 on Vold Linux on an x86_64 system.

**Comment by alexandervdm** [comment]
Confirmed this regression and re-added the code that prevents it. There are some significant improvements to be made to this code block, but I'm short on time so for now I'm just getting the fix out there through 0.8.2. Thanks for the report!
