### ISSUE TITLE
[ProductivityFeature] Remember preview positions for tabs

### ISSUE THREAD

**Issue by kravemir** [alexandervdm/gummi#15]
I'm using Gummi for LaTeX editting and it's great, but I miss one feature - remember preview positions for each tab.

I work a lot with multiple files / subfiles / included files into others, which together make whole document. Therefore I tend to switch between them quite often, but that preview scrolling each time is quite time consuming.

**Comment by kravemir** [comment]
Is anybody here??

**Comment by alexandervdm** [comment]
I thought we already did this, but if we don't it will be included for sure.

**Comment by kravemir** [comment]
WOW. Response after three years. I'm not using Gummi anymore, as I'm not university student anymore. No need for this, for me, anymore.

**Comment by alexandervdm** [comment]
Apologies for the late reply. It's a good idea all the same, so I'll implement it soon.

**Comment by alexandervdm** [comment]
Fixed, thanks for the report!

**Comment by kravemir** [comment]
Thank you for the fix!

Though, I don't use LaTeX anymore, as I'm not student anymore,.. I believe the fix will be beneficial to university students and workers.

**Comment by kravemir** [comment]
Do you plan to make a release? So, the change will get propagated to distributions?

**Comment by alexandervdm** [comment]
Yes, I'm putting the final touches on a 0.7.999 test build which after a period of testing will be succeeded by the 0.8.0 release.
