### ISSUE TITLE
SyncTex lookup fails on files with spaces

### ISSUE THREAD

**Issue by drakesiard** [alexandervdm/gummi#154]
**Describe the bug**
If the filename contains a space, you cannot Ctrl-click on a paragraph in the preview and move to the location in the source. 
The same file with underscores instead of spaces will work as expected.  

**To Reproduce**
1. Enable SyncTex
1. Open "without_spaces.tex"
3. Ctrl-click on text in the preview and observe the code highlight in the editor.
4. Open "with spaces.tex"
3. Ctrl-click on text in the preview and nothing happens.

**System:**
 - OS: Ubuntu 20.04.2 LTS 
 - Gummi: 0.8.1

[SyncTex test files.zip](https://github.com/alexandervdm/gummi/files/6165499/SyncTex.test.files.zip)

**Comment by drakesiard** [comment]
Can I also just add that not allowing .tex files as attachments seems somewhat unhelpful in this case?

**Comment by alexandervdm** [comment]
A fix for this bug has been committed to the repository, thanks for reporting!

Can you specify on what you mean with [your second question?](https://github.com/alexandervdm/gummi/issues/154#issuecomment-802050553)
