### ISSUE TITLE
Add feature to refuse saving when file has been changed externally

### ISSUE THREAD

**Issue by krichter722** [alexandervdm/gummi#16]
Currently `gummi` saves files based on the internal state. Changes in external editors are not reflected which causes the loss of external changes. `gummi` should memorize the content of the file when it was opened and compare it with the current content and refuse to save if it's not equal. The fact that a modification took place outside `gummi` needs to be handled externally. An option to reload the file from disk (i.e. overwrite changes in `gummi`) or to force saving (i.e. overwrite external changes) should be given.

experienced with 0.6.5-26-g6240b51

**Comment by alexandervdm** [comment]
Fixed by recent PR, thanks for reporting.
