### ISSUE TITLE
Cannot update from 0.8.1 to 0.8.2

### ISSUE THREAD

**Issue by iipr** [alexandervdm/gummi#160]
Following the steps from https://packages.gummi.app/ does not allow me to update from 0.8.1 to 0.8.2:
```
gummi is already the newest version (0.8.1-1ubuntu0.20.04.1).
```
The main reason why I want to update is https://github.com/alexandervdm/gummi/issues/143, which happens to me in Ubunut 20.04.

**Comment by Vectornaut** [comment]
Seconded! Is there anything I can do to help make 0.8.2 available through the Ubuntu Focal PPA?

**Comment by alexandervdm** [comment]
Long overdue, my bad. I bumped the focal package to 0.8.2 just now. Will bump the others if either of you can confirm all is OK.

**Comment by Vectornaut** [comment]
Thanks so much! Everything looks great so far. Issue #125 is fixed for me, as expected. I'll be using Gummi pretty much every day this week, so I should quickly notice any problems that affect my usual workflow.

**Comment by iipr** [comment]
Thanks a lot! I upgraded to 0.8.2 and #143 seems to be fixed.
