### ISSUE TITLE
Gummi can't see images unless it's root

### ISSUE THREAD

**Issue by NikiLentz** [alexandervdm/gummi#163]
Hi,
I am using gummi on Manjaro and I think this might just be a configuration problem, but I can't compile any document with pictures for a few days now. 
The pictures are accesible to all users and it worked until a week ago. Now I need to start gummi with sudo to get it to load images.

Any idea? Or am I out of luck here?

**Comment by alexandervdm** [comment]
You probably want to recheck the permissions on your source files/images and some folders like ~/.cache/gummi. In any case I very much doubt this is Gummi specific.
