### ISSUE TITLE
Please add Keywords to data/misc/gummi.desktop.in

### ISSUE THREAD

**Issue by danstender** [alexandervdm/gummi#18]
--- a/data/misc/gummi.desktop.in
+++ b/data/misc/gummi.desktop.in
@@ -8,5 +8,6 @@
 Terminal=false
 Type=Application
 Categories=Office;
+Keywords=latex;editor;
 StartupNotify=true
 MimeType=text/x-tex;

Thanks,
DS

**Comment by danstender** [comment]
This is patch out of Debian packaging:
https://sources.debian.net/src/gummi/0.6.5-4/debian/patches/gummi.desktop.patch/

**Comment by alexandervdm** [comment]
Committed in b886b37893b0c6ea20e7babffdec67b78a4e5111 - thank you!
