### ISSUE TITLE
Fedora repo link in the wiki is dead

### ISSUE THREAD

**Issue by guiand888** [alexandervdm/gummi#189]
Hi,

The link to the Fedora repo under [https://github.com/alexandervdm/gummi/wiki/Installing-Gummi#install-for-your-platform]() should be updated to [https://packages.fedoraproject.org/pkgs/gummi/gummi/]().

I would have gladly just sent a PR but the wiki is private.

Cheers!

**Comment by alexandervdm** [comment]
Removed the entry per reasoning in #190
