### ISSUE TITLE
please add link against libthread-2.0 in src/Makefile.am

### ISSUE THREAD

**Issue by danstender** [alexandervdm/gummi#19]
Could you please apply this patch from Debian packaging:
https://sources.debian.net/src/gummi/0.6.5-4/debian/patches/libgthread-2.0_link.patch/

Thanks,
DS

**Comment by alexandervdm** [comment]
Applied in 0a8c48c24eeb01bd7c1c81ad9431220c4cb5c28c. Thank you! New release soonish.

**Comment by danstender** [comment]
Great!

The new release gets into Debian immediately (I have upload rights).

Dan
