### ISSUE TITLE
[utils.c:128]: pointless allocation ?

### ISSUE THREAD

**Issue by dcb314** [alexandervdm/gummi#22]
[utils.c:128]: (style) Variable 'out' is allocated memory that is never used.

Source code is

       else
            out = g_strdup (message);

        dialog = gtk_message_dialog_new (parent,
                GTK_DIALOG_MODAL | GTK_DIALOG_DESTROY_WITH_PARENT,
                L_IS_TYPE (level,L_G_INFO)? GTK_MESSAGE_INFO: GTK_MESSAGE_ERROR,
                GTK_BUTTONS_OK,
                "%s", message);
        g_free (out);

**Comment by alexandervdm** [comment]
Good catch, fixed in d6d436d5c156d4fd6d517175e132240179ffad1f thanks!
