### ISSUE TITLE
[REQUEST] Include PPAs in Readme

### ISSUE THREAD

**Issue by JollyWizard** [alexandervdm/gummi#38]
_Edit_ Originally, I asked for .debs, but I found a third party post with a ppa.

Please reference this in the readme so that incoming users will not chase their tails trying to get this installed.

**Comment by alexandervdm** [comment]
The packages on our PPA and the distributions they targeted were rather outdated, so I've removed all the builds for now. Ubuntu's current release tracks our latest release at the moment, but I will re-instate the PPA if/when the two become misaligned again.
