### ISSUE TITLE
Bibliography Table shows nothing in Gummi

### ISSUE THREAD

**Issue by windmgc** [alexandervdm/gummi#4]
I'm using Gummi on Archlinux, and it's updated to 0.6.5-3 today. Yet I found that Gummi cannot auto-detect the bibliography as the way it worked before. Filename shows "none", and no references in the table. But I can still compile the bib file and after the compliation of whole file the References will show correctly at the end of the article.

**Comment by krichter722** [comment]
Please edit the title to something meaning- and thus helpful.

**Comment by alexandervdm** [comment]
Please re-open if this still occurs with the recent release, and if so please include an example file.
