### ISSUE TITLE
Is there auto completion function? If yes, how to set it?

### ISSUE THREAD

**Issue by lzhang6** [alexandervdm/gummi#44]
I am newbie in Latex and find gummi is easy to use.
Is there auto completion function? If yes, how to set it?
Waiting for your reply!

**Comment by SalathielGenese** [comment]
No sure... I think the last time I used it, there were code snippets options... Go on testing

**Comment by ernstblecha** [comment]
see https://github.com/alexandervdm/gummi/wiki/Using-Gummi#command-completion # #

**Comment by alexandervdm** [comment]
See #31
