### ISSUE TITLE
Install Error

### ISSUE THREAD

**Issue by dcon691** [alexandervdm/gummi#46]
I am trying to install the program into a specific directory, but whenever I try to run the configure script 
./autogen.sh

./configure --prefix=/path/to/directory

I get the following error
./configure: line 2152: syntax error near unexpected token `foreign'
./configure: line 2152: `AM_INIT_AUTOMAKE(foreign -Wall -Werror)'

Any help would be great!

**Comment by Alarnti** [comment]
You should use appropriate version of automake  described by AM_VERSION in autogen.sh. For instance I have 1.15

**Comment by alexandervdm** [comment]
I added some code to dynamically determine the version of automake available on your system. It should work now for all reasonably modern versions, but please re-open if you still run into issues.
