### ISSUE TITLE
Clicking "Project" and then "Open Project" results in segfault

### ISSUE THREAD

**Issue by danstender** [alexandervdm/gummi#5]
-------- Forwarded Message --------
Subject: Bug#785605: gummi: Clicking "Project" and then "Open Project" results in segfault.
Resent-Date: Mon, 18 May 2015 09:24:01 +0000
Resent-From: Charles L. <charles.debian.bug.reports@gmail.com>
Resent-To: debian-bugs-dist@lists.debian.org
Resent-CC: Debian Science Maintainers <debian-science-maintainers@lists.alioth.debian.org>
Date: Mon, 18 May 2015 03:18:05 -0600
From: Charles L. <charles.debian.bug.reports@gmail.com>
Reply-To: Charles L. <charles.debian.bug.reports@gmail.com>, 785605@bugs.debian.org
To: Debian Bug Tracking System <submit@bugs.debian.org>

Package: gummi
Version: 0.6.5-4
Severity: normal

Dear Maintainer,

Clicking on "project" and the "Open Project" results in segfault.

I used the debian wiki on backtracing to obtain the following: [GDB backtrace](http://pastebin.com/raw/Cuts4Qy8)

**Comment by danstender** [comment]
The missing system info from the bug report:

-- System Information:
Debian Release: stretch/sid
  APT prefers unstable
  APT policy: (500, 'unstable'), (1, 'experimental')
Architecture: amd64 (x86_64)
Foreign Architectures: i386

Kernel: Linux 3.16.0-4-amd64 (SMP w/8 CPU cores)
Locale: LANG=en_US.UTF-8, LC_CTYPE=en_US.UTF-8 (charmap=UTF-8)
Shell: /bin/sh linked to /bin/dash
Init: systemd (via /run/systemd/system)

Versions of packages gummi depends on:
ii  libc6                  2.21-0experimental0
ii  libcairo2              1.14.2-2
ii  libgdk-pixbuf2.0-0     2.31.1-2+b1
ii  libglib2.0-0           2.44.0-3
ii  libgtk2.0-0            2.24.25-3
ii  libgtksourceview2.0-0  2.10.5-2
ii  libgtkspell0           2.0.16-1.1
ii  libpango-1.0-0         1.36.8-3
ii  libpoppler-glib8       0.26.5-2
ii  libsynctex1            2014.20140926.35254-6

Versions of packages gummi recommends:
ii  texlive-extra-utils  2014.20141024-1
ii  texlive-latex-base   2014.20141024-2
ii  texlive-xetex        2014.20141024-2

Best,
Daniel Stender

**Comment by joksnet** [comment]
Same here:

```
[Info] Gummi version: svn800
[Info] configuration file: ~/.config/gummi/gummi.cfg
[Info] Texlive 2015 was found installed..
[Info] Typesetter detected: pdfTeX 3.14159265-2.6-1.40.16 (TeX Live 2015/Arch Linux)
[Info] Typesetter detected: XeTeX 3.14159265-2.6-0.99992 (TeX Live 2015/Arch Linux)
[Info] Typesetter detected: Latexmk 4.43a
[Info] snippets : ~/.config/gummi/snippets.cfg
[Debug] Gummi created!
[Info] using libpoppler 0.37.0
[Debug] GummiGui created!
[Info] Typesetter pdflatex configured.
[Thread][Debug] motion_compile_thread ()
[Thread][Debug] Compile thread sleeping...
[Info] setting styles scheme to classic
[Info] setting font to Monospace 10
[Info] 
[Info] Environment created for:
[Info] TEX: (null)
[Info] TMP: /tmp/gummi_63VH8X
[Info] PDF: /tmp/gummi_63VH8X.pdf
[Debug] motion_do_compile ()
[Thread][Debug] Compile thread awoke.
[Thread][Debug] Document size wrong for fitting, changing scale from 0.000000 to 0.473730.
[Thread][Debug] Compile thread sleeping...
[Debug] motion_do_compile ()
[Thread][Debug] Compile thread awoke.
[Thread][Debug] Compile thread sleeping...
[Debug] Document size wrong for fitting, changing scale from 0.473730 to 1.538782.
[1]    31534 segmentation fault (core dumped)  gummi -d
```

**Comment by alexandervdm** [comment]
@danstender took the liberty of editing your post. Your backtrace was referencing every issue in the tracker because of the '#{int}' strings.
