### ISSUE TITLE
Enter and Esc keys do not work as expected in Find dialog box

### ISSUE THREAD

**Issue by emo916math** [alexandervdm/gummi#58]
In the Find dialog box, search for something, say "a" in the default document. Then press Esc. The dialog quits, as expected, but the highlight moves to the _next_ instance of "a"! This is disruptive in documents containing some widely spaced instances of a search key.

Search for "a" repeatedly. When the "Bottom reached, search from top?" dialog box appears, pressing either Enter or Esc triggers the No button. It seems that Enter should trigger the Yes button.

For what it's worth, I'm running Gummi 0.6.5 in Linux Mint 17.3.

**Comment by d9h02f** [comment]
Nice find, I can reproduce it on 0.6.6 as well.

**Comment by alexandervdm** [comment]
Fixed in 2e02c67fb3e6efcd2940473a7d13eb4c6e8154ba, thanks for reporting!
