### ISSUE TITLE
Problem with autoconf

### ISSUE THREAD

**Issue by juanuni** [alexandervdm/gummi#59]
I'm trying to compile Gummi in Chakra Linux. Reading the INSTALL file I can see need create configure file by making autoconf, but this appears:

`$ autoconf`
 `     configure.ac:6: error: possibly undefined macro: AM_INIT_AUTOMAKE`
       `If this token and others are legitimate, please use m4_pattern_allow.` 
      `See the Autoconf documentation.`
`configure.ac:23: error: possibly undefined macro: AM_PROG_CC_C_O`
`configure.ac:35: error: possibly undefined macro: AM_PATH_GLIB_2_0`
`configure.ac:38: error: possibly undefined macro: AC_MSG_ERROR`
`configure.ac:45: error: possibly undefined macro: AM_PATH_GTK_2_0
`

Reading the issues here, I see this maybe is related to [https://github.com/alexandervdm/gummi/issues/46](url). Then I make `./autogen.sh` and the output is:

`$ ./autogen.sh`
    `  + '[' x '!=' x ']'`
    `  + aclocal-1.14`
     `  ./autogen.sh: línea 11: aclocal-1.14: no se encontró la orden`
     `  + autoheader`
      ` + AUTOMAKE=automake-1.14`
      ` + libtoolize -c --automake`
      ` + automake-1.14 --add-missing --copy --include-deps`
       ` ./autogen.sh: línea 14: automake-1.14: no se encontró la orden`
      `  + autoconf`
      `  + cp -f /usr/share/automake-1.14/mkinstalldirs .`
       `cp: no se puede efectuar 'stat' sobre '/usr/share/automake-1.14/mkinstalldirs': No existe el fichero o el directorio`
      ` + rm -rf autom4te.cache`
`
What is wrong? I'm forgetting something?

**Comment by cobalamin** [comment]
I can get beyond this by changing the `AM_VERSION=-1.14` to `AM_VERSION=-1.15` (may vary for you, check what `aclocal --version` outputs). After `configure`, the `make` step fails for me, so it'd be nice to know if that works for you after fixing the automake step.

**Comment by juanuni** [comment]
Thanks your suggestion works. Now I have another problem with dependences. I thinks I solve this soon. Regards

**Comment by alexandervdm** [comment]
Your original issue with autoconf version detection has been solved in a recent commit. Hope you managed to fix your dependencies also, otherwise let me know. Thanks.
