### ISSUE TITLE
Gummi does not cope with some file paths

### ISSUE THREAD

**Issue by kayvax** [alexandervdm/gummi#7]
Hi,
I would like to adres issue that is not quite serious but I found it annoying a bit.

Some times during usage I have encountered such thing:
! I can't find file `"/home/user/documents/study/school2012/5 Sem/111.111 Subject/Name_Surname_111.111/.Name_Surname_111.111.tex.swp"'.

When I copy work folder to other folder that is nested lower than */111.111 Subject/ it works.

I have tried to find if work folder was nested too much or folder names with spaces/numbers/dots reproduced this error and found that it may be that there may be loss of spaces during filepath processing. I have tried paths like:
/home/user/documents/new/new/new/file.tex
/home/user/documents/new/new new/new/file.tex
/home/user/documents/new/new new/new new/file.tex
and had no error. But I investigated my original path and found that there is double space  in */111.111 Subject/ so path in error is different than path showed in error.

And it does not seem that there is a difference between /new  new/ or /new  / or /  new/ - they all reproduce error.

I really do not know how Gummi works with paths and wether it is internal or external problem but this is something I encountered only in Gummi as Texmaker and LateXilla have no problems with such paths.

best regards,
kayvax

**Comment by alexandervdm** [comment]
I was not able to reproduce this issue, please re-open if the problem persists with Gummi's latest release.

**Comment by TooMuchRAM** [comment]
This is still an issue. Opening from a file share (such as Nextcloud) from Nautilus, Gummi shows the following in the build log:
```
This is pdfTeX, Version 3.141592653-2.6-1.40.22 (TeX Live 2021/Arch Linux) (preloaded format=pdflatex)
 \write18 enabled.
entering extended mode
! Emergency stop.
<*> ...ematical Structures/.assignment-01.tex.swp"
                                                  
!  ==> Fatal error occurred, no output PDF file produced!
Transcript written on ?.

```
After copying the file to Downloads and opening it again in Gummi, it does work.

Gummi version 0.8.2 on Arch Linux
