### ISSUE TITLE
Add nightly/dracula theme

### ISSUE THREAD

**Issue by saurabheights** [alexandervdm/gummi#75]
It would be good to have nightly theme like other IDES - Visual Studio, Idea, Eclipse, etc. If you agree, I can add this as PR.
P.S. - I am new to Gummi and Latex, so any tips from where to start would be helpful.

**Comment by d9h20f** [comment]
You can set a dark theme in GNOME Tweaks and Gummi will use it.

**Comment by saurabheights** [comment]
It will take some time for me to make gnome tweaks work for a single application, but for now I will close this issue. Will reopen if I face any issue. Thank you so much.
