### ISSUE TITLE
Wondering about the trick of instant previewing?

### ISSUE THREAD

**Issue by elliott-wen** [alexandervdm/gummi#80]
Hello, I am a crazy fan of LaTeX. I am so curious how gummi implemented the instant previewing?

Can I have any hints without looking at the source codes?

Cheers

**Comment by ajs124** [comment]
Isn't it the same as in every other LaTeX "ide", like TexStudio and TexMaker? It just waits until you haven't typed anything for a second or two, renders it with your specified renderer (like xelatex, pdflatex or luatex) converts it if needed and displays the pdf.

**Comment by alexandervdm** [comment]
That's pretty much it. If you need more (technical) details, please contact me directly.
