### ISSUE TITLE
What happened to this project? It seems pretty abandoned...

### ISSUE THREAD

**Issue by q2dg** [alexandervdm/gummi#85]
It's a pity

**Comment by alexanderadam** [comment]
If someone has the expertise:
maybe someone forks gummi and integrates the open PRs

**Comment by alexanderadam** [comment]
Hi Alexander,

no problem. It is absolutely understandable, everyone has a life outside of software development as well. :wink: 

These are very promising news! Thank you for answering.

@q2dg this issue here could be closed then, right? :thinking:

**Comment by q2dg** [comment]
Yes, of course!!
Thanks a lot!
