### ISSUE TITLE
BibTeX menu entry

### ISSUE THREAD

**Issue by shikadi** [alexandervdm/gummi#86]
When i click the "Run BibTeX" menu entry, it will be disabled, which doesn't seem to make sense. I have to run BibTeX again when i add new bibliography items. At the moment, i always have to close Gummi and start it again to re-enable it.

**Comment by progirep** [comment]
Same problem here.

**Comment by alexandervdm** [comment]
Fixed in 1891c5a338130f1c7ba7b56feb34a34954c6480a, thanks for reporting!
