### ISSUE TITLE
Add support for LuaTeX

### ISSUE THREAD

**Issue by tietzc** [alexandervdm/gummi#91]
LuaTeX is stable for quite some time and it would be really nice if Gummi had support for it.

Thank you for picking up development again. Gummi is still my favourite lightweight LaTeX editor.

**Comment by alexandervdm** [comment]
Support added by @karcsesz. Will be included in upcoming 0.8.0 release.

**Comment by tietzc** [comment]
Excellent. I do very much appreciate the effort.
