### ISSUE TITLE
Open files in UTF-8

### ISSUE THREAD

**Issue by marco74** [alexandervdm/gummi#93]
Gummi is a great LaTeX-Editor. Comparing it with two others Gummi does not have that many features that simple OS features do not work any more (like Ctrl+Shift+U for entering Unicode Characters).

**Describe the bug**
But I have one Problem with Gummi. When saving a file containing Greek letters, the file is saved properly as UTF-8-encoded Unicode (checked with hexedit), gedit can also open it. But when re-opening it with gummi, it is opened as ASCII.

Please provide UTF-8-support when opening files. 

**To Reproduce**
* Save following string to a file using gummi: αβγδεζηθικλμνξοπρσςτυφχψω
* Close the file
* Re-open the file again

**System:**
 - OS: Debian 9.5
 - Gummi version 0.6.6

**Comment by marco74** [comment]
Just managed to compile the original code of gummi. (Yeah, my Debian also uses the sid repository, therefore some other things are incompatible sometimes, but fortunately there's docker :-) ). This version decodes UTF-8 correctly. I think I have to talk with the debian team.

**Comment by WhoseTheNerd** [comment]
The problem is reproducible on Arch Linux as well.
