### ISSUE TITLE
How to change the font size of the build log?

### ISSUE THREAD

**Issue by ndgnuh** [alexandervdm/gummi#96]
**Describe the bug**
Text on build log is too small. I have to copy the whole log to another text editor to be able to read it (which is very inconvenient).

**To Reproduce**
Just build the tex file.

**System:**
- Archlinux
- Gummi 0.7.4

**Other**
![image](https://user-images.githubusercontent.com/33273948/48488385-3d1c6200-e853-11e8-9476-f67662b541fa.png)

**Comment by sfaleron** [comment]
I have this issue too on Arch.  Maybe it's some interaction with the distro?

**Comment by alexandervdm** [comment]
You were running a unofficial fork with this problem that Arch had packaged. This situation has been rectified and your fontsize should be bigger now. In a future release I'll make the fonts for this window configurable as well.
